__author__ = 'franciscoarcecardenas'
contextactivities = {
              '/activity/POO':[":5984/objetos/objetos/clases.jpg,play,imagen,1",":5984/objetos/objetos/descarga.jpg,play,imagen,2"],


              '/activity/protoboard': [{'url': ':5984/objetos/tec/protoboard1.png', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/1.png', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/videojuego2.mp4', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/agua.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/activity/manera': [{'url': ':5984/objetos/tec/protoboard3.png', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/3.png', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/agua.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/activity/quehago': [{'url': ':5984/objetos/tec/protoboard2.png', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/2.png', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/agua.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/activity/queuso':[{'url': ':5984/objetos/tec/protoboard4.png', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/tec/4.png', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/paraquesirvo': [{'url': ':5984/objetos/tec/protoboard5.png', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/tec/5.png', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/cantidad3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/cantidad.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testcantidad':[{'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetos/test.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/porciento': [{'url': ':5984/objetos/objetostrompo/porciento1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/porciento.mp4', 'estado': 'play', 'dispositivo': '2', 'tipo': 'video'} ,
                                        {'url': ':5984/objetos/objetostrompo/porciento3.gif', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/porciento.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testporciento':[{'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetostrompo/tests.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/energia': [{'url': ':5984/objetos/objetostrompo/energia1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/energia.mp4', 'estado': 'play', 'dispositivo': '2', 'tipo': 'video'} ,
                                        {'url': ':5984/objetos/objetostrompo/energia2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/energia .mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testenergia':[{'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetostrompo/tests.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/salud': [{'url': ':5984/objetos/objetostrompo/salud1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/salud.mp4', 'estado': 'play', 'dispositivo': '2', 'tipo': 'video'} ,
                                        {'url': ':5984/objetos/objetostrompo/salud3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/salud original.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testsalud':[{'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetostrompo/tests.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetostrompo/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/cicloagua': [{'url': ':5984/objetos/objetostrompo/cicloagua1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/cicloagua2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/cicloagua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/cicloagua.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testcicloagua':[{'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/materia': [{'url': ':5984/objetos/objetostrompo/materia1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/materia.mp4', 'estado': 'play', 'dispositivo': '2', 'tipo': 'video'} ,
                                        {'url': ':5984/objetos/objetostrompo/materia2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetostrompo/materia.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],
              '/test/testmateria':[{'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetostrompo/tests.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],

              '/activity/adios':[{'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetostrompo/agua3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],
              '/test/test':[{'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],



              '/woutobjects':[ ],
             }